### ISSUE TITLE
Доска

### ISSUE THREAD

**Issue by sheremet-va** [xesjkeee/vite-docs-ru#4]
Может сделать доску, чтобы при переводе не пересекаться? Можно поделить на разделы и забирать, кто над чем работает.

Или хоть как-то коммуницировать, а то страшно переводить некоторые разделы - может они уже на локальной машине переведены у другого человека :)

**Comment by xesjkeee** [comment]
@sheremet-va Напиши мне в телеграм `@xesjjj`
